name: Private NPM
description: Sets up NPM/Yarn to access private repositories
author: https://github.com/seek-jobs
public: true
requirements:
  - bash
configuration:
  properties:
    registry:
      type: string
    scope:
      type: string
    token:
      type: string
    env:
      type: string
    file:
      type: string
    output-path:
      type: string
