name: Private NPM
description: Sets up NPM/Yarn to access private repositories
author: https://github.com/seek-jobs
public: true
requirements:
  - bash
configuration:
  definitions:
    multi-registry-object:
      type: object
      properties:
        env:
          type: string
        path:
          type: string
  properties:
    multi-registries:
      type: array
      items:
        $ref: '#/definitions/multi-registry-object'
    registry:
      type: string
    token:
      type: string
    env:
      type: string
    file:
      type: string
    output-path:
      type: string

