#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

echo '--- Setting up access for :no_entry_sign: :npm: :package:'

REGISTRY=${BUILDKITE_PLUGIN_PRIVATE_NPM_REGISTRY:-'//registry.npmjs.org/'}
TOKEN=${BUILDKITE_PLUGIN_PRIVATE_NPM_TOKEN:=''}
FILE=${BUILDKITE_PLUGIN_PRIVATE_NPM_FILE:=''}
ENV=${BUILDKITE_PLUGIN_PRIVATE_NPM_ENV:=''}

if [[ -n "${FILE}" ]]
then
  TOKEN=$(cat "${FILE}")
elif [[ -n "${ENV}" ]]
then
  TOKEN="${!ENV}"
fi

[[ -z $TOKEN ]] && exit 1

cat > .npmrc << EOF
${REGISTRY}:_authToken=${TOKEN}
save-exact=true
EOF
